### ISSUE TITLE
Don't show debug information when imported

### ISSUE THREAD

**Issue by Richienb** [wilix-team/iohook#219]
## Expected Behavior
`iohook` should be imported without creating any noise in the terminal.

## Current Behavior
It is logging this:
```
refresh_locale_list [476]: GetKeyboardLayoutList(0, NULL) found 2 layouts.
refresh_locale_list [493]: Received 2 locales.
load_input_helper [866]: refresh_locale_list() found 2 locale(s).
```

## Possible Solution
Silently perform this in the background and only alert if failed.

## Steps to Reproduce (for bugs)
```js
require("iohook")
```

## Context
I want to be able to silently import `iohook` without it spitting information in the terminal.

## Your Environment

* Version used: 0.6.5
* Environment name and version (e.g. Chrome 39, node.js 5.4): Node.js 13.7.0
* Operating System and version (desktop or mobile): Windows 10

cc @Djiit

**Comment by Richienb** [comment]
@Djiit Ping!

**Comment by Richienb** [comment]
@Djiit Friendly ping!

**Comment by Djiit** [comment]
Hey there :-)

I'm sorry I don't have much free time these days.
Maybe you could open a PR with a proposed solution ?

**Comment by Richienb** [comment]
Sure! I was going to do that initially except I've been getting dabbed on by the build requirements.

**Comment by Djiit** [comment]
The code is *pretty old* as we speak. I'm more able to maintain the JS aspects, as I'm not the original author :), so yeah, any help is appreciated ! Thanks!

**Comment by Richienb** [comment]
After some investigating, it appears that this line is the culprit:

https://github.com/wilix-team/iohook/blob/master/libuiohook/src/logger.c#L42

**Comment by kwhat** [comment]
Somewhere in the native interface for this library, you can do something like this:

```
bool logger_proc(unsigned int level, const char *format, ...) {
    bool status = false;
    
    va_list args;
    switch (level) {
        #ifdef USE_DEBUG
        case LOG_LEVEL_DEBUG:
        case LOG_LEVEL_INFO:
            va_start(args, format);
            status = vfprintf(stdout, format, args) >= 0;
            va_end(args);
            break;
        #endif

        case LOG_LEVEL_WARN:
        case LOG_LEVEL_ERROR:
            va_start(args, format);
            status = vfprintf(stderr, format, args) >= 0;
            va_end(args);
            break;
    }
    
    return status;
}

...

hook_set_logger_proc(&logger_proc);
```

**Comment by kwhat** [comment]
I am not sure of node has a logging facility, but if it does, `logger_proc` should probably interface with it instead of std output.

**Comment by Richienb** [comment]
See: https://github.com/wilix-team/iohook/blob/cd1c5ae74c46d00e8739bee1dec66f58fb63e612/libuiohook/src/logger.c

**Comment by kwhat** [comment]
You shouldn't need to monkey around with libuiohook, only call `logger_proc` with a new function from iohook.cc.

**Comment by Richienb** [comment]
@kwhat I have no idea how to program in C++ but if we can somehow callback to the main script then it would be much easier to do logging.

**Comment by kwhat** [comment]
@Richienb just console.log?

**Comment by Richienb** [comment]
@kwhat `console.log` in C++?

**Comment by kwhat** [comment]
Sorry, I am a bit of a novice at node outside of just using NPM to get and build stuff.  It looks like iohook.cc already has a [logger function setup](https://github.com/wilix-team/iohook/blob/master/src/iohook.cc#L42), so the only thing that would need to be done would be to change that function to call a javascript function that does logging.  This is effectively what is happening in the [JNI](https://github.com/kwhat/jnativehook/blob/2.1/src/jni/jni_Logger.c#L97 example I provided earlier for the Java side of things.  This library provides no javascript logging facility, so I am trying to figure out what we would call back to in `logger_proc` which is why I was asking about `console.log`.  This function would just need to be updated to call out to the javascripts console methods to log instead of going out to stdout/stderr as it currently does.  As I previously stated, I don't know much about node, but this seems to be the most basic method of logging in node.  There are at least another 3 NPM logging libraries that do more advanced logging and the `logger_proc` method could easily interface with any number of those by either using some type of configuration or some yet to be created iohook javascript logging facility.  This logging facility would need to have a javascript method that is called from the native code directly (logger_proc) and it would need to call a callback function to do the logging.  There should also be a default callback function and a method of setting the current callback function.  There maybe a way to do this from the native code directly and just skip the javascript part, but it would probably be easier and cleaner to just do it in javascript.  I will have to do some more digging.

**Comment by Richienb** [comment]
@kwhat The easiest way to do this is to use a [Nan Callback](https://github.com/nodejs/nan/blob/master/doc/callback.md) to pass on all the arguments logger_proc is provided with.

**Comment by dk1-noida** [comment]
To stop the logs coming from iohook you need simply pass false in the start function
const ioHook = require('iohook');
ioHook.start(false);

**Comment by ash0x0** [comment]
Will make sure this is in docs.

**Comment by ash0x0** [comment]
Added to doc.
