### ISSUE TITLE
Not working on Mac M1

### ISSUE THREAD

**Issue by pie6k** [wilix-team/iohook#315]
Seems it is not possible to use this library on arm64 architecture (mac m1)

## Expected Behavior
Being able to use iohook on arm64

## Current Behavior
Having 'arm64' added to 'arches', I'm getting error:

```
[1] App threw an error during load
[1] Error: dlopen(<myapp>/node_modules/iohook/builds/electron-v87-darwin-arm64/build/Release/iohook.node, 1): no suitable image found.  Did find:
[1] 	<myapp>/node_modules/iohook/builds/electron-v87-darwin-arm64/build/Release/iohook.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
[1] 	<myapp>/node_modules/iohook/builds/electron-v87-darwin-arm64/build/Release/iohook.node: unknown file type, first eight bytes: 0x7F 0x45 0x4C 0x46 0x02 0x01 0x01 0x00
```

## Possible Solution
¯\_(ツ)_/¯ 

## Steps to Reproduce (for bugs)

1. Add architecture of arm64 to package.json
2. Install this lib on Mac M1
3. Try to use it\

## Your Environment

* Version used: 0.9.0
* Environment name and version Electron 12.0
* Operating System and version (desktop or mobile): MacOS 11.2.3\

**Comment by WilixLead** [comment]
We still don't have configured environment for build it in arms. You can build it manually in your mac. I think it should work

**Comment by ash0x0** [comment]
This will probably not be addressed anytime soon. Simply because the support for M1 is not really there yet for node native and because it's not that impactful of an issue to address at the moment. If anyone is interested in helping out with M1 support please feel free to reopen this for discussion and PR if you're working on it or if you believe there's a quick way to add this feel free to suggest as well.

**Comment by jeremypagley** [comment]
@pie6k Did you ever find a solution for this as I am running into the same issue and don't want to go buy a new Intel Mac just to fix this problem

**Comment by apodolny** [comment]
Given that all Mac laptops are now arm64, should this be reopened? Understand there may be limited resources to devote, but not supporting this is basically saying once the desktop intel macs are phased out, this library won't support Macs at all. 

Would be open to devoting some work to this, but want to make sure it's a priority for the project. I've had trouble getting it to build on M1 using the manual build documentation, so would like to draw more attention here and see if we can get a group together to solve this.

**Comment by raphaelmenges** [comment]
I have managed to build the `.node` and `.dylib` on my Mac M1 by executing `npm run build`, but I am lost on how to integrate these in the context of the JavaScript API of iohook. A package generated with`npm pack` does contain the `.node` and `.dylib` but not the index.js etc.

**Comment by marcelblum** [comment]
@raphaelmenges if you want to test your build you can just do a regular `npm install iohook` and then manually copy your built `.node` & `.dylib` into the folder where iohook expects to find it. This folder name is concatenated from the platform, arch, environment version etc. at https://github.com/wilix-team/iohook/blob/229774494c7c338936d0596acd3f4693d363ea39/index.js#L5-L20
I don't know exactly what that works out to in your environment but would be something like `node_modules\iohook\builds\electron-v87-darwin-arm64\build\Release\`.

Haven't tried this yet on an M1, please report back on your results!

**Comment by raphaelmenges** [comment]
@marcelblum I could not use `npm install iohook` on my Mac because the installation fails as it does not find a prebuild binary. Thus, I have installed iohook on my Windows machine and copied the `iohook` directory from the `node_modules` directory to a minimal Node.js project on my Mac. In addition, I have cloned the source repository from GitHub on my Mac and generated the binary `.node` and `.dylib` files. I copied both files into the iohook folder under `node_modules` into `builds\node-v83-darwin-arm64`. Implementing the basic usage example from the documentation, iohook seems to work as expected:

<img width="100%" src="https://user-images.githubusercontent.com/4311739/142592204-e3e7c9fe-0fc5-4e79-83d8-2e203149ba75.png">

This workflow may be feasible for private projects. However, I hope one can suggest me how to make the installation process convenient across paltforms. I have seen in other issues that the automatic build system of iohook should be able to generate binaries for M1. However, it would be already feasible if one could install the iohook module without prebuilt binaries and use a npm postintall hook to generate the required binaries after installation.

PS: I also added a keydown hook to my code. However, after being triggered once iohook did not trigger any further callback, whether it is a mouse or a keyboard event. Is this expected behavior? Perhaps I should investigate this in more detail and create a separate issue.

**Comment by marcelblum** [comment]
@raphaelmenges ah I see why that wouldn't work to `npm install iohook` since it throws an error which halts the whole rest of the install process if the prebuild isn't found, sorry for my bad suggestion 😅 . The relevant lines are here I think just changing this from `throw` to `console.error` should allow it to install https://github.com/wilix-team/iohook/blob/229774494c7c338936d0596acd3f4693d363ea39/install.js#L15-L17

But also there's a trick you should be able to use to get it to install via `npm install iohook` which is to force specify an incorrect but existing platform in your `package.json` as per the instructions at https://wilix-team.github.io/iohook/usage.html. In other words, if you have a supported platform specified in `package.json` before you `npm install`, it will default to downloading that existing prebuild and not break the install, overriding the autodetected current platform/arch.

**Comment by raphaelmenges** [comment]
I have prebuilt the binaries for my target plattforms and everything seems to work as expected. I am looking forward for a future version of iohook that either includes the prebuilds I need or builds locally at installation. Perhaps I will fork and try to implement the local build myself, let's see 🤔 Thanks so far @marcelblum!

**Comment by marcelblum** [comment]
@raphaelmenges just curious aside from the issues installing the package, did you have to modify any code to get it to build or did 'npm run build' just work?
