### ISSUE TITLE
iohook.node is not valid Win32 application

### ISSUE THREAD

**Issue by nemyagky** [wilix-team/iohook#320]
I've created very simple electron + iohook app: https://github.com/magmiv/electron-iohook-test

When I'm launching it - I'm getting this error
![image](https://user-images.githubusercontent.com/48682276/115764243-ff21b180-a3ad-11eb-8490-081f9ed3f52f.png)

I'm using 
Node.js v12.13.0 (on 14.15.4 also doesn't work)
Electron 12.0.5
Iohook 0.9.0

Could you tell me, where I'm wrong? Thank you so much in advance

**Comment by magmiv** [comment]
Downgrading electon version works for me

**Comment by ash0x0** [comment]
So the issue causing this for everyone's future reference is because iohook relies on a prebuild system to get binaries. Prebuilds are matched with three things: 1. OS, 2. Node version, 3. Electron version. Which means that if there is no prebuild available for this specific iohook release for your exact combination of your OS, node and electron versions then you won't be able to install.
This is on the agenda to move from a prebuild system for install to a node native build.
