### ISSUE TITLE
Cannot find module 'iohook' during installation

### ISSUE THREAD

**Issue by callejoadrian** [wilix-team/iohook#334]
iohook is working properly in my development platform. Compiling the program is also working.
But when I tried to install the .exe file this error appear...

![Capture123](https://user-images.githubusercontent.com/37166080/121290447-3413a480-c919-11eb-98cd-234e5b32fd9a.PNG)

If I remove the iohook in my program, the installation is successful and this message does not appear.

## Expected Behavior

No problem on installation and iohook is working.

## Current Behavior

error while installing the program

## Steps to Reproduce (for bugs)

1. I manually add the binary file in my nodes_modules/iohook/builds folder
2. npm run make (I used electron forge)
3. go to /out/make/squirrel.windows/x64/file.exe
4. install the .exe file

## Your Environment

* electron v12.0.6
* node v12.13.1
* os: windows10 x64

![image](https://user-images.githubusercontent.com/37166080/121291713-51e20900-c91b-11eb-85fd-e62cf39bea81.png)

**Comment by callejoadrian** [comment]
@marcelblum hi good day! btw i forgot to mention that iohook folder is missing in the install path. sorry I'm new in electron/node. how/what im going to update in my forge config? and probably, Im not using ASAR. thanks for the reply.

**Comment by marcelblum** [comment]
Is iohook listed in your package.json under `dependencies`?

**Comment by callejoadrian** [comment]
![image](https://user-images.githubusercontent.com/37166080/121454338-31768500-c9d5-11eb-8b4f-3ee736839cfa.png)

these are my dependencies. I also tried to add
"iohook": "^0.9.1"

but an error occur when i tried to compile it.

**Comment by marcelblum** [comment]
Ok so sounds like since you compiled it yourself, you just manually placed a iohook folder in your node_modules and never did a `npm install iohook`. Forge definitely won't automagically know to include iohook in your packaged app since it's not listed in your `dependencies`. I think the easiest thing for you to do would be to create another node_modules folder inside your /src/ folder and move your custom iohook folder inside that /src/node_modules. That way it should be automatically included in your app package by Forge as part of your app's source code, and then it should be automatically found by your app when it does a `require('iohook')` because `require` will search that relative node_modules path for it.

Alternatively, you can use the [extraResource](https://electron.github.io/electron-packager/master/interfaces/electronpackager.options.html#extraresource) option in your [Forge packager config](https://www.electronforge.io/configuration#packager-config) to specify that the iohook folder be copied over during the packaging process.

**Comment by callejoadrian** [comment]
Yes. i just copy and paste the iohook binary file since `npm install iohook` is not working.

_create another node_modules folder inside your /src/ folder and move your custom iohook folder inside that /src/node_modules_

this directions works for me. thanks for the help @marcelblum.

**Comment by ash0x0** [comment]
@callejoadrian why is `npm install iohook` not working for you?

**Comment by callejoadrian** [comment]
@ash0x0 I just tried it today. now its all working. but last time(maybe last 2 weeks?) I cannot download the package and it returns an 404 error message.

**Comment by callejoadrian** [comment]
@ash0x0 thank you so much for the updates.
